// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjk37BGWcn2y9K3MDmZF7o_GlEXMyY5Q',
    appId: '1:364240486503:web:5abc9578e6c6ac04a2d4c2',
    messagingSenderId: '364240486503',
    projectId: 'furniture-web-9067d',
    authDomain: 'furniture-web-9067d.firebaseapp.com',
    storageBucket: 'furniture-web-9067d.firebasestorage.app',
    measurementId: 'G-QG4MWBTPDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46X01utd_8GMlBaNTZWXSj5QMrn-ToG4',
    appId: '1:364240486503:android:6db5e37ab3378fb6a2d4c2',
    messagingSenderId: '364240486503',
    projectId: 'furniture-web-9067d',
    storageBucket: 'furniture-web-9067d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_su9ExXLb5Q9kJiRgg81EstCqj-bgbFA',
    appId: '1:364240486503:ios:fe7ed01996e9fc43a2d4c2',
    messagingSenderId: '364240486503',
    projectId: 'furniture-web-9067d',
    storageBucket: 'furniture-web-9067d.firebasestorage.app',
    iosBundleId: 'com.example.furnitureWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_su9ExXLb5Q9kJiRgg81EstCqj-bgbFA',
    appId: '1:364240486503:ios:fe7ed01996e9fc43a2d4c2',
    messagingSenderId: '364240486503',
    projectId: 'furniture-web-9067d',
    storageBucket: 'furniture-web-9067d.firebasestorage.app',
    iosBundleId: 'com.example.furnitureWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCjk37BGWcn2y9K3MDmZF7o_GlEXMyY5Q',
    appId: '1:364240486503:web:a72788dc59398937a2d4c2',
    messagingSenderId: '364240486503',
    projectId: 'furniture-web-9067d',
    authDomain: 'furniture-web-9067d.firebaseapp.com',
    storageBucket: 'furniture-web-9067d.firebasestorage.app',
    measurementId: 'G-J42EXV50EM',
  );
}
