import 'package:flutter/widgets.dart';
import 'package:furniture_web/model/product_model.dart';
import 'package:furniture_web/utlis/constants/app_assets.dart';

class ProductProvider with ChangeNotifier {
  
  final List<ProductModel> _adProducts = [
    ProductModel(
      prodId: '0',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.n_a_sofa_2],
      discountPrice: 690,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '1',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.n_a_sofa_3],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '2',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.n_a_sofa_4],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '3',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.n_a_sofa_5],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '4',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.n_a_sofa_6],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '5',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.n_a_sofa_8],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '6',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.a_sofa_49],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '7',
      title: 'Ashton 3 + 2 Seater Sofa',
      description:
          'Luxurious Ashton 3+2 seater sofa in plush fabric, offering elegant style and firm comfort for any modern living space.',
      price: 690,
      condition: 'New',
      listOfImages: [AppAssets.a_sofa_50],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '8',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_77],
      discountPrice: 690.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '9',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_9],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '10',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa__6],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '11',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_66],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '12',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_62],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '13',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa__38],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '14',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_43],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '15',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_67],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '16',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.n_v_sofa_1],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '17',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.n_v_sofa_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '18',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.n_v_sofa_5],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '19',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_80],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '20',
      title: 'Verona 5 Seater Sofa',
      description:
          'Luxurious Verona 5-seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.n_v_sofa_6],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '21',
      title: 'Verona 3+2 Seater Sofa',
      description:
          'Luxurious Verona 3+2 seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 540,
      condition: 'New',
      listOfImages: [AppAssets.n_v_sofa_3],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '22',
      title: 'Verona 3+2 Seater Sofa',
      description:
          'Luxurious Verona  3+2 seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 570,
      condition: 'New',
      listOfImages: [AppAssets.n_v_sofa_4],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '23',
      title: 'Verona 3+2 Seater Sofa',
      description:
          'Luxurious Verona  3+2 seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 570,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_42],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '24',
      title: 'Verona 2 Seater ',
      description:
          'Luxurious Verona 2 seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 290,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_47],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '25',
      title: 'Verona 2 Seater ',
      description:
          'Luxurious Verona 2 seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 290,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_40_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '26',
      title: 'Verona 3+2 Seater Sofa',
      description:
          'Luxurious Verona 3+2 seater sofa in soft napple fabric, offering elegant style and firm comfort for your living space.',
      price: 540,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_48],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '27',
      title: 'Roma 3+2 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 710,
      condition: 'New',
      listOfImages: [AppAssets.roma_sofa],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '28',
      title: 'Roma 3 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.r_sofa_53],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '29',
      title: 'Roma 3 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.r_sofa_54],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '30',
      title: 'Roma 3+2 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 710,
      condition: 'New',
      listOfImages: [AppAssets.r_sofa_55],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '31',
      title: 'Roma 3 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.n_r_sofa_1],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '32',
      title: 'Roma 3+2 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 710,
      condition: 'New',
      listOfImages: [AppAssets.n_r_sofa_3],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '33',
      title: 'Roma 3 Seater Sofa',
      description:
          'Premium Roma leather recliner sofa, blending luxurious comfort with modern functionality for the ultimate relaxation experience',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.n_r_sofa_5],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '34',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 590,
      condition: 'New',
      listOfImages: [AppAssets.u_sofa_12_2, AppAssets.u_sofa_12],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '35',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.u_sofa_10_2, AppAssets.u_sofa_10],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '36',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.n_u_sofa_1],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '37',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.n_u_sofa_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '38',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.n_u_sofa_4],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '39',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.n_u_sofa_5],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '40',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.u_sofa_73],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '41',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.u_sofa_11],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '42',
      title: 'Grand 6 Seater U-Saped Sofa',
      description:
          'Spacious U-shaped sofa offering modern style, generous seating, and exceptional comfort for family gatherings or lounging',
      price: 580,
      condition: 'New',
      listOfImages: [AppAssets.u_sofa_13_2, AppAssets.u_sofa_13],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '43',
      title: 'Luxury 5-Seater Corner Sofa',
      description:
          'Elegant Cornor 5-seater sofa in plush fabric, offering stylish design and firm comfort for any modern living space.',
      price: 470,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_4],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '44',
      title: 'Luxury 5-Seater Corner Sofa',
      description:
          'Elegant Cornor 5-seater sofa in plush fabric, offering stylish design and firm comfort for any modern living space.',
      price: 470,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_5],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '45',
      title: 'Luxury 5-Seater Corner Sofa',
      description:
          'Elegant Cornor 5-seater sofa in plush fabric, offering stylish design and firm comfort for any modern living space.',
      price: 470,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_6],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '46',
      title: 'Luxury 5-Seater Corner Sofa',
      description:
          'Elegant Cornor 5-seater sofa in plush fabric, offering stylish design and firm comfort for any modern living space.',
      price: 470,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_7],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '47',
      title: 'Luxury 5-Seater Corner Sofa',
      description:
          'Elegant Cornor 5-seater sofa in plush fabric, offering stylish design and firm comfort for any modern living space.',
      price: 470,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '48',
      title: 'Luxury 5-Seater Corner Sofa',
      description:
          'Elegant Cornor 5-seater sofa in plush fabric, offering stylish design and firm comfort for any modern living space.',
      price: 470,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_75],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '49',
      title: 'Cornor 5 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 450,
      condition: 'New',
      listOfImages: [AppAssets.v_sofa_18, AppAssets.v_sofa_18],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '50',
      title: 'Cornor 5 Seater Sofa',
      description:
          'Luxurious corner sofa in soft napple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 450,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_14],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '83',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft plush fabric, combining modern elegance with supreme comfort for your living space.',
      price: 410,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '51',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_22],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '52',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_26],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '53',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_7],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '54',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_71],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '55',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 390,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_72],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '56',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft plush fabric, combining modern elegance with supreme comfort for your living space.',
      price: 410,
      condition: 'New',
      listOfImages: [AppAssets.l_sofa_1],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '57',
      title: 'Dylan 3+2 Seater Sofa',
      description:
          'Luxury 3+2 seater dylan sofa in soft chenille fabric, offering timeless style and exceptional comfort for any living space.',
      price: 400,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_82, AppAssets.s_sofa_81],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '58',
      title: 'Dylan 3 Seater Sofa',
      description:
          'Luxury 3-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 250,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_4],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '59',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 220,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_35_1, AppAssets.s_sofa_36],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '60',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 220,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_21],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '61',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 240,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_30_2, AppAssets.s_sofa_30],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '62',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft plush fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 260,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_1_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '63',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 260,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_31],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '64',
      title: 'Grand 3+2 Seater Sofa',
      description:
          'Luxury 3+2-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 440,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_34_2, AppAssets.s_sofa_32],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '65',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft chenille fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 260,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_32],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '66',
      title: 'Dylan 2 Seater Sofa',
      description:
          'Luxury 2-seater Dylan sofa upholstered in soft plush fabric, designed to bring a refined touch and inviting comfort to your TV lounge',
      price: 260,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_33_3, AppAssets.s_sofa_33],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '67',
      title: 'Dylan 3+2 Seater Sofa',
      description:
          'Luxury 3+2 seater dylan sofa in soft chenille fabric, offering timeless style and exceptional comfort for any living space.',
      price: 400,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_52],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '68',
      title: 'Dylan 3+2 Seater Sofa',
      description:
          'Luxury 3+2 seater dylan sofa in soft chenille fabric, offering timeless style and exceptional comfort for any living space.',
      price: 400,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_51],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '69',
      title: 'Dylan 3+2 Seater Sofa',
      description:
          'Luxury 3+2 seater dylan sofa in soft chenille fabric, offering timeless style and exceptional comfort for any living space.',
      price: 400,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_68, AppAssets.s_sofa_74],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '70',
      title: 'Verona 3+2 Seater',
      description:
          'Premium 3+2 seater Dylan sofa in soft Plush fabric,cosy feel, perfect for creating a welcoming atmosphere in your home.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_78],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '71',
      title: 'Verona 3+2 Seater',
      description:
          'Premium 3+2 seater Dylan sofa in soft Plush fabric,cosy feel, perfect for creating a welcoming atmosphere in your home.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_58],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '72',
      title: 'Verona 3+2 Seater',
      description:
          'Premium 3+2 seater Dylan sofa in soft Plush fabric, cosy feel, perfect for creating a welcoming atmosphere in your home.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.s_sofa_79],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '73',
      title: 'Verona 3+2 Seater',
      description:
          'Premium 3+2 seater Dylan sofa in soft Plush fabric,cosy feel, perfect for creating a welcoming atmosphere in your home.',
      price: 490,
      condition: 'New',
      listOfImages: [AppAssets.n_s_sofa_2],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '74',
      title: 'Verona 2 Seater',
      description:
          'Premium 2 seater Dylan sofa in soft Plush fabric, cosy feel, perfect for creating a welcoming atmosphere in your home.',
      price: 290,
      condition: 'New',
      listOfImages: [AppAssets.n_s_sofa_3],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '75',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 380,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_5],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '76',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 380,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_23],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '77',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 380,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_15],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '78',
      title: 'Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 380,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_19],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '79',
      title: 'dylan Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 370,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_24],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '80',
      title: 'dylan Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 370,
      condition: 'New',
      listOfImages: [AppAssets.c_sofa_63],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
    ProductModel(
      prodId: '81',
      title: 'dylan Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 370,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_1],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),

    ProductModel(
      prodId: '82',
      title: 'dylan Cornor 4 Seater Sofa',
      description:
          'Luxurious corner sofa in soft naple fabric, combining modern elegance with supreme comfort for your living space.',
      price: 370,
      condition: 'New',
      listOfImages: [AppAssets.n_c_sofa_3],
      discountPrice: 1799.99,
      isSold: false,
      createdAt: DateTime.now().subtract(Duration(days: 2)),
    ),
  ];

  List<ProductModel> get adProducts => _adProducts;
}
